### ISSUE TITLE
Nice idea!

### ISSUE THREAD

**Issue by upchuk** [mikecrittenden/drupal-7-deconstructed#1]
Hey Mike,

Just wanted to say that it's a really nice idea this one! 

Good luck!

**Comment by crittermike** [comment]
Hey @upchuk, thanks a ton! I'm really excited about this! 

BTW, not sure if it's obvious yet, but http://www.drupaldeconstructed.com is a thing now - it syncs with the GitHub repo so should always be up to date, and allows you to subscribe to updates.
