### ISSUE TITLE
Change cover.jpg

### ISSUE THREAD

**Issue by alesrebec** [mikecrittenden/drupal-7-deconstructed#21]
I think current Arduino cover might mislead people on their first glance of an eye.
I like the idea of deconstructed content. I just think you should put something else there. 

Maybe something like this. It's more generic.
![deconstructed](https://cloud.githubusercontent.com/assets/426177/9732324/4b382196-5623-11e5-8f47-3dbef588e115.jpg)
And I would put a Druplicon over one of the items.

**Comment by crittermike** [comment]
Thanks for the idea! Went with another one from the set that has the one you linked to, and added a Druplicon. http://www.drupaldeconstructed.com/

Thanks!
