### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by RuZniki** [mikecrittenden/drupal-7-deconstructed#26]
I've just read few chapters and find it very easy to read for me.
I would like to help you to translate this book to russian.
What do you think about it?
What license do you use for this book?

**Comment by crittermike** [comment]
Hey there, I have no objections to a Russian translation, I think that's a great idea. Feel free to fork the repo and start translating, and we can go from there! I can link to it from the README once you've made some progress.

Let's say that the license is creative commons attribution.
