### ISSUE TITLE
What is the licence of this material? Permission to use it for the Backdrop CMS documentation

### ISSUE THREAD

**Issue by klonos** [mikecrittenden/drupal-7-deconstructed#39]
Hello @crittermike and @rhuffstedtler 👋🏼 ...thank you for the time/effort/energy you have put into this 🙏🏼 

Since Backdrop CMS is the continuation of Drupal 7, we were wondering if you would be OK with us either porting this material over and/or using portions of it for our documentation. Show us some open-source ❤️ please?

**Comment by crittermike** [comment]
Oh please do! I'd love it if this ended up continuing to be useful to someone in the world! Just let me how I can be helpful.

**Comment by rhuffstedtler** [comment]
Agreed!

**Comment by klonos** [comment]
Thank you both @crittermike and @rhuffstedtler 🙏🏼 

It may be a while till the entire thing is forked/ported/tweaked (might end up in https://docs.backdropcms.org instead of GitHub after all), but it's definitely helpful, since most things that applied in D7 still apply in Backdrop.

H/T to both of you gents 🎩 

(I'll go ahead and close this then 😉 )
