### ISSUE TITLE
In 03-router.md, clarification would be useful on when menu_rebuild() is called

### ISSUE THREAD

**Issue by rhuffstedtler** [mikecrittenden/drupal-7-deconstructed#4]
I've never thought about this one myself. I assume it happens during a cache clear, or possibly in response to some modules like page_manager, but I don't actually know. A couple of concrete examples of common reasons might help contextualize that section better for the user.

Doing a quick grep for things that set menu_rebuild_needed, I'm kind of surprised at how often it has to happen!

**Comment by crittermike** [comment]
@rhuffstedtler See attached commit and let me know what you think. That was a fun and interesting rabbit hole!

**Comment by crittermike** [comment]
More readable link: https://github.com/mikecrittenden/drupal-7-deconstructed/blob/ea5893233bd4835e90a27b4e9ee5eff81af6ca89/03-router.md#when-does-this-happen

**Comment by crittermike** [comment]
Going to close this for now @rhuffstedtler but feel free to reopen if you think anything is still missing.
